#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Heartbeat runner — crontab-driven periodic agent tasks
# Subcommands: sync (default), run, stop, status, migrate
# ---------------------------------------------------------------------------

HEARTBEAT_DIR="${HOME}/.heartbeat"
LOG_FILE="${HEARTBEAT_DIR}/heartbeat.log"
ENV_FILE="${HEARTBEAT_DIR}/env.sh"
WORKSPACE="${HOME}/harness/workspace"
CONFIG_FILE="${WORKSPACE}/heartbeats.conf"
LEGACY_FILE="${WORKSPACE}/HEARTBEAT.md"  # backward compat for users who haven't migrated
SOUL_FILE="${SOUL_FILE:-${WORKSPACE}/SOUL.md}"
MEMORY_DIR="${MEMORY_DIR:-${WORKSPACE}/memory}"

HEARTBEAT_AGENT="${HEARTBEAT_AGENT:-claude}"
HEARTBEAT_ACTIVE_START="${HEARTBEAT_ACTIVE_START:-}"
HEARTBEAT_ACTIVE_END="${HEARTBEAT_ACTIVE_END:-}"
HEARTBEAT_INTERVAL="${HEARTBEAT_INTERVAL:-1800}"
LOG_MAX_LINES="${HEARTBEAT_LOG_MAX_LINES:-1000}"

CRON_MARKER="# heartbeat-managed"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log() {
  local ts
  ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "[$ts] $*" | tee -a "$LOG_FILE"
}

rotate_log() {
  if [[ -f "$LOG_FILE" ]]; then
    local lines
    lines=$(wc -l < "$LOG_FILE")
    if (( lines > LOG_MAX_LINES )); then
      tail -n 500 "$LOG_FILE" > "${LOG_FILE}.tmp" && mv "${LOG_FILE}.tmp" "$LOG_FILE"
      log "Log rotated (was ${lines} lines)"
    fi
  fi
}

# Returns 0 (true) if file is effectively empty (skip heartbeat).
is_heartbeat_empty() {
  local file="$1"
  [[ ! -f "$file" ]] && return 1

  local content
  content=$(sed 's/<!--[^>]*-->//g' "$file" \
    | sed ':a;N;$!ba;s/<!--[^>]*-->//g' \
    | grep -vE '^\s*$' \
    | grep -vE '^\s*#{1,6}\s' \
    | grep -vE '^\s*[-*+]\s*$' \
    | grep -vE '^\s*[-*+]\s*\[[ xX]?\]\s*$' \
    || true)

  [[ -z "$content" ]]
}

# Returns 0 if within active hours (or if not configured).
# Accepts optional override via positional args.
is_active_hours() {
  local start="${1:-$HEARTBEAT_ACTIVE_START}"
  local end="${2:-$HEARTBEAT_ACTIVE_END}"

  [[ -z "$start" || -z "$end" ]] && return 0

  local hour
  hour=$(date +%H | sed 's/^0//')

  if (( start <= end )); then
    (( hour >= start && hour < end ))
  else
    (( hour >= start || hour < end ))
  fi
}

# Returns 0 if response is a HEARTBEAT_OK acknowledgment.
is_heartbeat_ok() {
  local response="$1"
  (( ${#response} < 300 )) && [[ "$response" == *"HEARTBEAT_OK"* ]]
}

# Convert seconds to a 5-field cron expression.
seconds_to_cron() {
  local seconds="$1"
  local minutes=$((seconds / 60))

  if (( minutes <= 0 )); then
    echo "* * * * *"
  elif (( minutes < 60 )); then
    echo "*/${minutes} * * * *"
  elif (( minutes == 60 )); then
    echo "0 * * * *"
  elif (( minutes < 1440 )); then
    local hours=$((minutes / 60))
    echo "0 */${hours} * * *"
  else
    echo "0 0 * * *"
  fi
}

# Generate env.sh so cron jobs inherit API keys, PATH, etc.
generate_env() {
  {
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by heartbeat.sh sync — do not edit"
    echo "export HOME='${HOME}'"
    echo "export PATH='${PATH}'"
    echo "export USER='${USER:-sandbox}'"
    # Capture API keys and relevant env vars
    env | grep -E '^(ANTHROPIC_|OPENAI_|HEARTBEAT_|GH_|GITHUB_|AGENTMAIL_|NODE_|NPM_|BUN_)' \
      | sed "s/'/'\\\\''/g" \
      | sed "s/^\\([^=]*\\)=\\(.*\\)$/export \\1='\\2'/" \
      || true
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

# ---------------------------------------------------------------------------
# cmd_run <file> [agent] [active_range]
# Single heartbeat execution — called by cron
# ---------------------------------------------------------------------------

cmd_run() {
  local file="${1:?Usage: heartbeat.sh run <file> [agent] [active_range]}"
  local agent="${2:-$HEARTBEAT_AGENT}"
  local active_range="${3:-}"

  mkdir -p "$HEARTBEAT_DIR" "$MEMORY_DIR"

  # Resolve relative path
  if [[ "$file" != /* ]]; then
    file="${WORKSPACE}/${file}"
  fi

  local basename
  basename=$(basename "$file" .md)

  # Per-file flock to prevent overlapping runs
  local lock_file="${HEARTBEAT_DIR}/${basename}.lock"
  exec 200>"$lock_file"
  if ! flock -n 200; then
    log "[${basename}] Skipping — previous execution still running"
    return 0
  fi

  # Gate: active hours (per-entry override or global)
  local active_start="" active_end=""
  if [[ -n "$active_range" && "$active_range" == *-* ]]; then
    active_start="${active_range%-*}"
    active_end="${active_range#*-}"
  fi
  if ! is_active_hours "$active_start" "$active_end"; then
    log "[${basename}] Outside active hours, skipping"
    return 0
  fi

  # Gate: empty file
  if is_heartbeat_empty "$file"; then
    log "[${basename}] File is effectively empty, skipping"
    return 0
  fi

  local heartbeat_content
  heartbeat_content=$(cat "$file")

  # Build prompt — inject SOUL.md if present
  local prompt=""
  if [[ -f "$SOUL_FILE" ]] && [[ -s "$SOUL_FILE" ]]; then
    prompt="$(cat "$SOUL_FILE")

---

"
  fi

  local today
  today=$(date -u +"%Y-%m-%d")

  prompt="${prompt}You are performing a periodic heartbeat check. Read the heartbeat content below and follow its instructions strictly.

If all tasks are complete or nothing needs attention, reply with exactly: HEARTBEAT_OK
If any task requires action, perform it and report what you did. Keep responses concise.

If you learn anything worth remembering long-term, append it to memory/${today}.md (create the memory/ directory and file if needed).

---
${basename}:
${heartbeat_content}
---"

  log "[${basename}] Running heartbeat (agent: ${agent})"

  local response="" exit_code=0

  case "$agent" in
    claude)
      response=$(timeout 300 claude -p "$prompt" --dangerously-skip-permissions 2>&1) || exit_code=$?
      ;;
    codex)
      response=$(timeout 300 codex "$prompt" 2>&1) || exit_code=$?
      ;;
    *)
      response=$(timeout 300 "$agent" -p "$prompt" 2>&1) || exit_code=$?
      ;;
  esac

  if (( exit_code == 124 )); then
    log "[${basename}] Timed out (300s limit)"
    return 0
  elif (( exit_code != 0 )); then
    log "[${basename}] Failed (exit code ${exit_code}): ${response:0:500}"
    return 0
  fi

  if is_heartbeat_ok "$response"; then
    log "[${basename}] HEARTBEAT_OK"
  else
    log "[${basename}] Response:"
    echo "$response" | tee -a "$LOG_FILE"
  fi

  rotate_log
}

# ---------------------------------------------------------------------------
# cmd_sync — parse config and install crontab entries
# ---------------------------------------------------------------------------

cmd_sync() {
  mkdir -p "$HEARTBEAT_DIR" "$MEMORY_DIR"
  generate_env

  local entries=()

  if [[ -f "$CONFIG_FILE" ]]; then
    # Parse heartbeats.conf
    while IFS= read -r line || [[ -n "$line" ]]; do
      # Skip comments and blank lines
      [[ "$line" =~ ^[[:space:]]*# ]] && continue
      [[ -z "${line// /}" ]] && continue

      # Parse: <cron 5 fields> | <file> | [agent] | [active_range]
      local cron_expr="" file_path="" agent="" active_range=""

      # Split on pipe
      IFS='|' read -ra parts <<< "$line"
      (( ${#parts[@]} < 2 )) && continue

      cron_expr=$(echo "${parts[0]}" | xargs)
      file_path=$(echo "${parts[1]}" | xargs)
      agent=$(echo "${parts[2]:-}" | xargs)
      active_range=$(echo "${parts[3]:-}" | xargs)

      [[ -z "$cron_expr" || -z "$file_path" ]] && continue

      # Validate file exists
      local full_path="$file_path"
      if [[ "$full_path" != /* ]]; then
        full_path="${WORKSPACE}/${full_path}"
      fi
      if [[ ! -f "$full_path" ]]; then
        log "Warning: file not found: ${full_path} (skipping)"
        continue
      fi

      # Build crontab line
      local entry="${cron_expr} . ${ENV_FILE} && ${HOME}/install/heartbeat.sh run \"${file_path}\" \"${agent}\" \"${active_range}\" >> ${LOG_FILE} 2>&1 ${CRON_MARKER}"
      entries+=("$entry")
    done < "$CONFIG_FILE"

  elif [[ -f "$LEGACY_FILE" ]]; then
    # Legacy mode: single HEARTBEAT.md with HEARTBEAT_INTERVAL
    local cron_expr
    cron_expr=$(seconds_to_cron "$HEARTBEAT_INTERVAL")
    local active_range=""
    if [[ -n "$HEARTBEAT_ACTIVE_START" && -n "$HEARTBEAT_ACTIVE_END" ]]; then
      active_range="${HEARTBEAT_ACTIVE_START}-${HEARTBEAT_ACTIVE_END}"
    fi

    # Check for legacy HEARTBEAT.md or default heartbeats/default.md
    local legacy_target="heartbeats/default.md"
    if [[ -f "$LEGACY_FILE" ]]; then
      legacy_target="HEARTBEAT.md"
    fi

    local entry="${cron_expr} . ${ENV_FILE} && ${HOME}/install/heartbeat.sh run \"${legacy_target}\" \"${HEARTBEAT_AGENT}\" \"${active_range}\" >> ${LOG_FILE} 2>&1 ${CRON_MARKER}"
    entries+=("$entry")
    log "Legacy mode: using ${legacy_target} with interval ${HEARTBEAT_INTERVAL}s (${cron_expr})"
  else
    log "No heartbeats.conf or HEARTBEAT.md found — nothing to sync"
    return 0
  fi

  # Preserve non-heartbeat crontab entries
  local existing=""
  existing=$(crontab -l 2>/dev/null | grep -v "$CRON_MARKER" || true)

  # Install new crontab
  {
    if [[ -n "$existing" ]]; then
      echo "$existing"
    fi
    for entry in "${entries[@]}"; do
      echo "$entry"
    done
  } | crontab -

  log "Synced ${#entries[@]} heartbeat schedule(s)"

  # Show what was installed
  for entry in "${entries[@]}"; do
    # Extract just cron + file for display
    local display
    display=$(echo "$entry" | sed "s| \. ${ENV_FILE} &&.*run ||" | sed "s| >>.*||")
    echo "  ${display}"
  done
}

# ---------------------------------------------------------------------------
# cmd_stop — remove all heartbeat crontab entries
# ---------------------------------------------------------------------------

cmd_stop() {
  local existing=""
  existing=$(crontab -l 2>/dev/null || true)

  if [[ -z "$existing" ]]; then
    echo "No crontab entries found."
    return 0
  fi

  local filtered
  filtered=$(echo "$existing" | grep -v "$CRON_MARKER" || true)

  if [[ -z "$filtered" ]]; then
    crontab -r 2>/dev/null || true
  else
    echo "$filtered" | crontab -
  fi

  log "All heartbeat schedules removed"
  echo "Heartbeat schedules removed."
}

# ---------------------------------------------------------------------------
# cmd_status — show schedules and recent logs
# ---------------------------------------------------------------------------

cmd_status() {
  # Check cron daemon
  if pgrep -x cron >/dev/null 2>&1; then
    echo "Cron daemon: running"
  else
    echo "Cron daemon: NOT running"
  fi

  echo ""

  # Show heartbeat crontab entries
  local entries=""
  entries=$(crontab -l 2>/dev/null | grep "$CRON_MARKER" || true)

  if [[ -n "$entries" ]]; then
    local count
    count=$(echo "$entries" | wc -l)
    echo "Heartbeat schedules: ${count}"
    echo "$entries" | while IFS= read -r line; do
      # Extract cron expression and file for display
      local cron_part file_part
      cron_part=$(echo "$line" | awk '{print $1, $2, $3, $4, $5}')
      file_part=$(echo "$line" | grep -oP 'run "\K[^"]+' || echo "?")
      echo "  ${cron_part}  →  ${file_part}"
    done
  else
    echo "Heartbeat schedules: none"
  fi

  # Show recent logs
  if [[ -f "$LOG_FILE" ]]; then
    echo ""
    echo "Recent log:"
    tail -n 10 "$LOG_FILE"
  fi
}

# ---------------------------------------------------------------------------
# cmd_migrate — convert legacy HEARTBEAT_INTERVAL to heartbeats.conf
# ---------------------------------------------------------------------------

cmd_migrate() {
  if [[ -f "$CONFIG_FILE" ]]; then
    echo "heartbeats.conf already exists — not overwriting."
    echo "Edit it directly: ${CONFIG_FILE}"
    return 1
  fi

  local cron_expr
  cron_expr=$(seconds_to_cron "$HEARTBEAT_INTERVAL")

  local active_line=""
  if [[ -n "$HEARTBEAT_ACTIVE_START" && -n "$HEARTBEAT_ACTIVE_END" ]]; then
    active_line=" | ${HEARTBEAT_AGENT} | ${HEARTBEAT_ACTIVE_START}-${HEARTBEAT_ACTIVE_END}"
  fi

  mkdir -p "${WORKSPACE}/heartbeats"

  # Migrate legacy HEARTBEAT.md content into heartbeats/default.md
  if [[ -f "$LEGACY_FILE" && ! -f "${WORKSPACE}/heartbeats/default.md" ]]; then
    mv "$LEGACY_FILE" "${WORKSPACE}/heartbeats/default.md"
    echo "Moved HEARTBEAT.md → heartbeats/default.md"
  fi

  cat > "$CONFIG_FILE" << EOF
# Heartbeat Schedule Configuration
# =================================
# Format: <cron-expression> | <file-path> | [agent] | [active_start-active_end]
#
# - cron-expression: Standard 5-field cron (min hour dom mon dow)
# - file-path: Relative to ~/harness/workspace/
# - agent: (optional) Override HEARTBEAT_AGENT env var. Default: ${HEARTBEAT_AGENT}
# - active_start-active_end: (optional) Hours (0-23). Only run during this window.
#
# Examples:
#   */30 * * * * | heartbeats/default.md
#   */15 * * * * | heartbeats/check-deployments.md | claude | 9-18
#   0 */4 * * *  | heartbeats/memory-distill.md
#   0 20 * * *   | heartbeats/daily-summary.md
#
# After editing, run: heartbeat.sh sync (or from host: make heartbeat)

${cron_expr} | heartbeats/default.md${active_line}
EOF

  echo "Created: ${CONFIG_FILE}"
  echo "  Schedule: ${cron_expr} (from HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}s)"
  echo ""
  echo "Add more heartbeats by editing heartbeats.conf and placing .md files in heartbeats/"
  echo "Then run: heartbeat.sh sync"
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

usage() {
  echo "Usage: heartbeat.sh {sync|run|stop|status|migrate}" >&2
  echo "" >&2
  echo "  sync      Install crontab entries from heartbeats.conf (default)" >&2
  echo "  run       Execute a single heartbeat (called by cron)" >&2
  echo "  stop      Remove all heartbeat crontab entries" >&2
  echo "  status    Show schedules and recent logs" >&2
  echo "  migrate   Convert HEARTBEAT_INTERVAL to heartbeats.conf" >&2
  exit 1
}

case "${1:-sync}" in
  sync|start) cmd_sync ;;
  run)        shift; cmd_run "$@" ;;
  stop)       cmd_stop ;;
  status)     cmd_status ;;
  migrate)    cmd_migrate ;;
  *)          usage ;;
esac
